### ISSUE TITLE
Doesn't work on Android 14

### ISSUE THREAD

**Issue by turismsur** [Marko2155/14blox#1]
hello, i am on a realme C55 running android 14 and 14blox doesn't work. Please fix this

**Comment by Marko2155** [comment]
yeah... i'm hosting it on a local server so that's probably why
fixing the bug now by hosting it on Render instead

**Comment by Marko2155** [comment]
reopening to update it incase something happens

**Comment by Marko2155** [comment]
fixed :D check latest release

**Comment by turismsur** [comment]
still doesn't work bro. it says "App not installed as app isn't compatible with your phone."

**Comment by Marko2155** [comment]
it's not compatible with your phone.
you need something close to an armeabi-v7a

**Comment by Marko2155** [comment]
i can't fix it, i'm not that good at Android development
i'm usually a full-stack developer in things like Node.js
